// Mocks generated by Mockito 5.4.0 from annotations
// in village_officer_app/test/database_helper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i2;
import 'package:village_officer_app/database_helper.dart' as _i3;
import 'package:village_officer_app/family_member.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i3.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> initDatabase({String? customPath}) => (super.noSuchMethod(
        Invocation.method(
          #initDatabase,
          [],
          {#customPath: customPath},
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> replaceDatabase(String? newDatabaseFilePath) =>
      (super.noSuchMethod(
        Invocation.method(
          #replaceDatabase,
          [newDatabaseFilePath],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertFamilyMember(_i5.FamilyMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertFamilyMember,
          [member],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.FamilyMember>> retrieveFamilyMembers() =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveFamilyMembers,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.FamilyMember>>.value(<_i5.FamilyMember>[]),
      ) as _i4.Future<List<_i5.FamilyMember>>);

  @override
  _i4.Future<List<_i5.FamilyMember>> retrieveFamilyMembersByHousehold(
          String? householdNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #retrieveFamilyMembersByHousehold,
          [householdNumber],
        ),
        returnValue:
            _i4.Future<List<_i5.FamilyMember>>.value(<_i5.FamilyMember>[]),
      ) as _i4.Future<List<_i5.FamilyMember>>);

  @override
  _i4.Future<void> deleteFamilyByHousehold(String? householdNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteFamilyByHousehold,
          [householdNumber],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteFamilyMemberById(int? Id) => (super.noSuchMethod(
        Invocation.method(
          #deleteFamilyMemberById,
          [Id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateFamilyData(
    String? householdNumber,
    Map<String, dynamic>? updatedData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFamilyData,
          [
            householdNumber,
            updatedData,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<int> updateFamilyMember(_i5.FamilyMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFamilyMember,
          [member],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> updateDateOfModified(_i5.FamilyMember? member) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDateOfModified,
          [member],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> updateFamilyDateOfModified(String? householdNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateFamilyDateOfModified,
          [householdNumber],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> getFamilyMemberData(
          String? householdNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #getFamilyMemberData,
          [householdNumber],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> querySamurdhiFamilies() =>
      (super.noSuchMethod(
        Invocation.method(
          #querySamurdhiFamilies,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryAswasumaFamilies() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryAswasumaFamilies,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryWedihitiFamilies() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryWedihitiFamilies,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryMahajanadaraFamilies() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryMahajanadaraFamilies,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryAbhadithaFamilies() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryAbhadithaFamilies,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryShishshyadaraFamilies() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryShishshyadaraFamilies,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryPilikadaraFamilies() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryPilikadaraFamilies,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryTuberculosisAidFamilies() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryTuberculosisAidFamilies,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryAnyAidFamilies() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryAnyAidFamilies,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryAllStudentFamilyMembers({
    required int? minAge,
    required int? maxAge,
    required String? dateOfModifiedPattern,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #queryAllStudentFamilyMembers,
          [],
          {
            #minAge: minAge,
            #maxAge: maxAge,
            #dateOfModifiedPattern: dateOfModifiedPattern,
          },
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryReligionFamilyMembers() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryReligionFamilyMembers,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryNationalityFamilyMembers() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryNationalityFamilyMembers,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> queryHigherEducationFamilyMembers() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryHigherEducationFamilyMembers,
          [],
        ),
        returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
            <Map<String, dynamic>>[]),
      ) as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<Map<String, List<_i5.FamilyMember>>> getPeopleBasedOnAgeGroups() =>
      (super.noSuchMethod(
        Invocation.method(
          #getPeopleBasedOnAgeGroups,
          [],
        ),
        returnValue: _i4.Future<Map<String, List<_i5.FamilyMember>>>.value(
            <String, List<_i5.FamilyMember>>{}),
      ) as _i4.Future<Map<String, List<_i5.FamilyMember>>>);

  @override
  _i4.Future<Map<String, List<_i5.FamilyMember>>>
      getPeopleBasedOnAgeGroupsLegally() => (super.noSuchMethod(
            Invocation.method(
              #getPeopleBasedOnAgeGroupsLegally,
              [],
            ),
            returnValue: _i4.Future<Map<String, List<_i5.FamilyMember>>>.value(
                <String, List<_i5.FamilyMember>>{}),
          ) as _i4.Future<Map<String, List<_i5.FamilyMember>>>);

  @override
  _i4.Future<List<_i5.FamilyMember>> queryGovernmentEmployees() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryGovernmentEmployees,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.FamilyMember>>.value(<_i5.FamilyMember>[]),
      ) as _i4.Future<List<_i5.FamilyMember>>);

  @override
  _i4.Future<List<_i5.FamilyMember>> queryPrivateEmployees() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryPrivateEmployees,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.FamilyMember>>.value(<_i5.FamilyMember>[]),
      ) as _i4.Future<List<_i5.FamilyMember>>);

  @override
  _i4.Future<List<_i5.FamilyMember>> querySemiGovernmentEmployees() =>
      (super.noSuchMethod(
        Invocation.method(
          #querySemiGovernmentEmployees,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.FamilyMember>>.value(<_i5.FamilyMember>[]),
      ) as _i4.Future<List<_i5.FamilyMember>>);

  @override
  _i4.Future<List<_i5.FamilyMember>> queryCorporationEmployees() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryCorporationEmployees,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.FamilyMember>>.value(<_i5.FamilyMember>[]),
      ) as _i4.Future<List<_i5.FamilyMember>>);

  @override
  _i4.Future<List<_i5.FamilyMember>> queryForcesEmployees() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryForcesEmployees,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.FamilyMember>>.value(<_i5.FamilyMember>[]),
      ) as _i4.Future<List<_i5.FamilyMember>>);

  @override
  _i4.Future<List<_i5.FamilyMember>> queryPoliceEmployees() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryPoliceEmployees,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.FamilyMember>>.value(<_i5.FamilyMember>[]),
      ) as _i4.Future<List<_i5.FamilyMember>>);

  @override
  _i4.Future<List<_i5.FamilyMember>> querySelfEmployedEmployees() =>
      (super.noSuchMethod(
        Invocation.method(
          #querySelfEmployedEmployees,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.FamilyMember>>.value(<_i5.FamilyMember>[]),
      ) as _i4.Future<List<_i5.FamilyMember>>);

  @override
  _i4.Future<List<_i5.FamilyMember>> queryNoJobEmployees() =>
      (super.noSuchMethod(
        Invocation.method(
          #queryNoJobEmployees,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.FamilyMember>>.value(<_i5.FamilyMember>[]),
      ) as _i4.Future<List<_i5.FamilyMember>>);

  @override
  _i4.Future<bool> isHouseholdNumberUnique(String? householdNumber) =>
      (super.noSuchMethod(
        Invocation.method(
          #isHouseholdNumberUnique,
          [householdNumber],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Future<bool> isNationalIdUnique(String? nationalId) =>
      (super.noSuchMethod(
        Invocation.method(
          #isNationalIdUnique,
          [nationalId],
        ),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
